#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENGINE_DIR="$(dirname "$SCRIPT_DIR")"
SHADER_DIR="$ENGINE_DIR/Shaders"

echo "Building shaders..."

# embed_pair <vert> <frag> <out_header>
# Compiles vert/frag to SPIR-V and embeds both as byte arrays in out_header,
# named "<stem>_vert_spv"/"<stem>_frag_spv" to match what Renderer.cpp expects.
embed_pair() {
    local vert="$1" frag="$2" out="$3"

    glslc "$SHADER_DIR/$vert.vert" -o "$SHADER_DIR/$vert.vert.spv" || { echo "Failed to compile $vert.vert"; exit 1; }
    glslc "$SHADER_DIR/$frag.frag" -o "$SHADER_DIR/$frag.frag.spv" || { echo "Failed to compile $frag.frag"; exit 1; }

    echo "// Auto-generated by BuildShaders.sh — do not edit" > "$out"
    echo "#pragma once" >> "$out"
    echo "" >> "$out"

    xxd -i "$SHADER_DIR/$vert.vert.spv" | \
        sed 's/unsigned/inline unsigned/g' | \
        sed "s/_home_.*_${vert}_vert_spv/${vert}_vert_spv/g" >> "$out"

    echo "" >> "$out"

    xxd -i "$SHADER_DIR/$frag.frag.spv" | \
        sed 's/unsigned/inline unsigned/g' | \
        sed "s/_home_.*_${frag}_frag_spv/${frag}_frag_spv/g" >> "$out"

    rm -f "$SHADER_DIR/$vert.vert.spv" "$SHADER_DIR/$frag.frag.spv"
    echo "Done → $out"
}

embed_pair default default "$ENGINE_DIR/include/Core/Rendering/DefaultShaders.hpp"
embed_pair ui      ui      "$ENGINE_DIR/include/Core/UI/UIShaders.hpp"
