#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENGINE_DIR="$(dirname "$SCRIPT_DIR")"
SHADER_DIR="$ENGINE_DIR/Shaders"
OUT_HEADER="$ENGINE_DIR/include/Core/Rendering/DefaultShaders.hpp"

echo "Building shaders..."

# Compile
glslc "$SHADER_DIR/default.vert" -o "$SHADER_DIR/default.vert.spv" || { echo "Failed to compile default.vert"; exit 1; }
glslc "$SHADER_DIR/default.frag" -o "$SHADER_DIR/default.frag.spv" || { echo "Failed to compile default.frag"; exit 1; }

# Embed into header
# Embed into header
echo "// Auto-generated by build_shaders.sh — do not edit" > "$OUT_HEADER"
echo "#pragma once" >> "$OUT_HEADER"
echo "" >> "$OUT_HEADER"

xxd -i "$SHADER_DIR/default.vert.spv" | \
    sed 's/unsigned/inline unsigned/g' | \
    sed 's/_home_.*_default_vert_spv/default_vert_spv/g' >> "$OUT_HEADER"

echo "" >> "$OUT_HEADER"

xxd -i "$SHADER_DIR/default.frag.spv" | \
    sed 's/unsigned/inline unsigned/g' | \
    sed 's/_home_.*_default_frag_spv/default_frag_spv/g' >> "$OUT_HEADER"


# Clean
rm -f "$SHADER_DIR"/*.spv

echo "Done → $OUT_HEADER"
